language: c
compiler:
  - gcc
  - clang

env:
  - VER_NEWRELIC_C_SDK=1.0.3
  - VER_OPENRESTY=1.9.9.1

sudo: false

addons:
  apt:
    packages:
      - lua5.1
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev

install:
  - mkdir ./vendor && cd ./vendor
  - wget wget http://openresty.org/download/ngx_openresty-${VER_OPENRESTY}.tar.gz && tar -xf ngx_openresty-${VER_OPENRESTY}.tar.gz
  - cd ngx_openresty-${VER_OPENRESTY}/
  - ./configure --prefix=/opt/openresty && make && sudo make install && cd ..
  - export PATH=/opt/openresty/nginx/sbin:$PATH
  - wget https://github.com/newrelic/c-sdk/archive/refs/tags/v${VER_NEWRELIC_C_SDK}.tar.gz && tar -xf "v{$VER_NEWRELIC_C_SDK}.tar.gz"
  - cd v${VER_NEWRELIC_C_SDK}
  - make
  - ar -x libnewrelic.a
  - gcc -shared -lnewrelic -lpcre -lm -lpthread -rdynamic *.o -o libnewrelic.so
  - sudo mkdir -p /usr/local/lib && sudo cp libnewrelic.so /usr/local/lib/
  - sudo ldconfig
script: make test